import * as v_5_8 from "https://cdn.jsdelivr.net/npm/vega-lite@5.8.0/+esm";
import * as v_5_14 from "https://cdn.jsdelivr.net/npm/vega-lite@5.14.1/+esm";
import * as v_5_15 from "https://cdn.jsdelivr.net/npm/vega-lite@5.15.1/+esm";
import * as v_5_16 from "https://cdn.jsdelivr.net/npm/vega-lite@5.16.3/+esm";
import * as v_5_17 from "https://cdn.jsdelivr.net/npm/vega-lite@5.17.0/+esm";
import * as v_5_20 from "https://cdn.jsdelivr.net/npm/vega-lite@5.20.1/+esm";
import * as v_5_21 from "https://cdn.jsdelivr.net/npm/vega-lite@5.21.0/+esm";
import * as v_6_1 from "https://cdn.jsdelivr.net/npm/vega-lite@6.1.0/+esm";
import * as v_6_4 from "https://cdn.jsdelivr.net/npm/vega-lite@6.4.1/+esm";
import * as vega from "https://cdn.jsdelivr.net/npm/vega@6.2.0/+esm";
import * as vegaThemes from "https://cdn.jsdelivr.net/npm/vega-themes@3.0.0/+esm";
import * as vegaEmbed from "https://cdn.jsdelivr.net/npm/vega-embed@7.0.2/+esm";
import lodashDebounce from "https://cdn.jsdelivr.net/npm/lodash.debounce@4.0.8/+esm";
