[package]
name = "vl-convert-vendor"
version = "0.0.0"
edition.workspace = true
license.workspace = true
readme = "README.md"
homepage = "https://github.com/vega/vl-convert"
repository.workspace = true
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
zip-extract = { workspace = true }
tempfile = { workspace = true }
anyhow = { workspace = true }
dircpy = { workspace = true }
semver = { workspace = true }
