name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vl-convert-python-tests-windows-debug:
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh
    env:
      RUST_MIN_STACK: 8388608
      RUST_BACKTRACE: 1
    steps:
      - name: Enable long paths on Windows
        run: git config --system core.longpaths true
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.47.0
      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v2.8.2
        with:
          prefix-key: "v1-rust"
          cache-on-failure: True
      - name: Install NASM (Windows)
        uses: ilammy/setup-nasm@v1
      - name: Build package
        run: pixi run dev-py
      - name: Run fontsource test only
        run: |
          pixi run pytest vl-convert-python/tests/test_specs.py::test_png_fontsource -v -s
      - name: Upload failed images
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: failed-images-python-windows-debug
          path: vl-convert-python/tests/failed/
